// <auto-generated />
namespace StaffManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateEmployeeModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateEmployeeModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202305181432430_updateEmployeeModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
